name: CreateResult
on:
  push:
    branches:
      - main
jobs:
  creategif:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: make
      - name: creategif
        run: docker-compose run --rm shell julia demo/gif/gif.jl
      - name: upload result to release page
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          tag: result/latest
          artifacts: result.gif
          token: ${{ secrets.GITHUB_TOKEN }}
